"""
Django settings for auth project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import base64
import dotenv
from cryptography.hazmat.primitives import serialization
dotenv.load_dotenv()

JWT_SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'your-very-secret-key')
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_SECONDS = 3600  # 1 hour

# Get keys
sender_private_key_pem = os.getenv("SENDER_PRIVATE_KEY3", "").replace("\\n", "\n").strip()
sender_public_key_pem = os.getenv("SENDER_PUBLIC_KEY4", "").replace("\\n", "\n").strip()
receiver_public_key_pem = os.getenv("RECEIVER_PUBLIC_KEY2", "").replace("\\n", "\n").strip()

if receiver_public_key_pem and sender_private_key_pem and sender_public_key_pem:
    try:

        RECEIVER_PUBLIC_KEY = serialization.load_pem_public_key(
            receiver_public_key_pem.encode("utf-8")
        )

        SENDER_PRIVATE_KEY = serialization.load_pem_private_key(
            sender_private_key_pem.encode("utf-8"),
            password=None
        )

        SENDER_PUBLIC_KEY = serialization.load_pem_public_key(
            sender_public_key_pem.encode("utf-8")
        )

    except ValueError as e:
        raise RuntimeError(f"Error loading RSA keys: {e}")

else:
    RECEIVER_PRIVATE_KEY = None
    RECEIVER_PUBLIC_KEY = None
    SENDER_PRIVATE_KEY = None
    SENDER_PUBLIC_KEY = None
    raise RuntimeError("RSA keys are missing in the environment variables.")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1g&b$++!820s*enlh*%7(zw#xh#yqn6u(fhaqsqqmzw38hs!f1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'seeding_users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auth.middleware.JWTAuthenticationMiddleware',
]

ROOT_URLCONF = 'auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
